### ISSUE TITLE
add scope for sorting students by their total score for an assessment

### ISSUE THREAD

**Issue by dustinbrownman** [epicodus/epicenter#101]
Right now the logic that handles sorting students on the assessment report is in the view. This is not ideal. We eventually need to add a scope to handle this. Unfortunately, the way we calculate student score is through a fairly hairy method `Assessment#final_total_score_for(student)`. That method will have to be cleaned up before this can be solved.

**Comment by chrisjoywebb** [comment]
Moving all issues to PivotalTracker.
