### ISSUE TITLE
Internship information & Ratings

### ISSUE THREAD

**Issue by JakeKaad** [epicodus/epicenter#118]
<h3> Description </h3>
<p>
Rian and Luke are building an internship and ratings application in Sinatra.  I am looking at what it would take to port the idea is to port it into the Epicenter.
</p>

<h3> Summary of additions </h3>
<p>
We would need to add only ( I think) 2 models.  Internship & InternshipRating.   Internships would belong to a cohort to keep them organized by class.  InternshipRating would use a join table, belonging to a user and an internship.   
</p>
<p>
2 controllers and associated routes<br>
  Internship with actions index, show, new, create, edit, update, delete <br>
  InternshipRating with actions new, create, edit, update
</p>
<p>
Views with their supported admin only features
</p>
<p>
Model specs, controller specs, integration spec
</p>

<h3>Anything else?</h3>
<p>
Is there something I didn't cover in here that I would need to make this a useful addition to epicenter?
</p>

**Comment by michaelrkn** [comment]
Come find me and we can chat about it :)

**Comment by JakeKaad** [comment]
Is there a way we can fake API keys for testing?

**Comment by michaelrkn** [comment]
Yeah, just make a free account with Balanced and Mailgun.
