### ISSUE TITLE
Change "Assessments" to "Code Reviews"

### ISSUE THREAD

**Issue by dustinbrownman** [epicodus/epicenter#135]
Not sure if we should change the actual model, or just in the UI...

**Comment by michaelrkn** [comment]
Both!

**Comment by dustinbrownman** [comment]
In addition to this, I'm considering renaming "requirements" to "objectives". Thoughts?

**Comment by michaelrkn** [comment]
i like it!

**Comment by kellywerks** [comment]
Yes!!

**Comment by dustinbrownman** [comment]
Merged! #151
