### ISSUE TITLE
'FROM_EMAIL_REVIEW'

### ISSUE THREAD

**Issue by JakeKaad** [epicodus/epicenter#140]
I think this ENV variable is the reason why tests are failing on my end.  What can I set this to to get my tests to pass?  
I don't have these set:
<p><code> FROM_EMAIL_PAYMENT</code></p>
<p><code>FROM_EMAIL_REVIEW</code></p>

**Comment by JakeKaad** [comment]
I don't have these set:
<p> <code> FROM_EMAIL_PAYMENT
FROM_EMAIL_REVIEW
</code></p>

**Comment by michaelrkn** [comment]
You can set them to anything you please, so long as it's a valid email address.

FYI, Github issues are good for filing bugs and documenting feature requests, not for asking for help with a specific problem you're having fixing a bug or implementing a feature. This issue, for example, should just be part of the discussion on your open pull request, or just an email you send to me.
