### ISSUE TITLE
Epicodus IP address

### ISSUE THREAD

**Issue by JakeKaad** [epicodus/epicenter#141]
We were trying to figure out a way that users could log-in from their paired computer in class, rather than having the master check-in.  We noticed that devise keeps track of the ip you are currently signed in on.  

Could we use the Epicodus IP to validate that you are at school, on the epicodus network to make sure that you are checking in at school.  Would there be a better way to verify this?

**Comment by michaelrkn** [comment]
I'd suggest keeping it simple for now - if you and your pair log in together, you're signed in. Unless you convince another student to scheme with you when you're both playing hooky, this should be security enough to get going :)

Future versions could use an agent running on the Epicodus network that reports the current Epicodus IP (we have a dynamic IP address) and then verifies it against the IP of the user signing in.

**Comment by michaelrkn** [comment]
As I noted in the other issue, this isn't really appropriate for an issue. I'm going to close this out; please open a new issue with the feature that you're working to implement, and then things like this can be part of the discussion on the issue. Thanks!
