### ISSUE TITLE
Students unable to sign in 

### ISSUE THREAD

**Issue by JakeKaad** [epicodus/epicenter#172]
It appears that students who didn't sign out the day before are unable to sign in the next day.  The "I'm Here" button doesn't appear and instead, both the "✓ Signed out" and "✓ Signed in" are there.

**Comment by dustinbrownman** [comment]
Hmm, we're seeing something a little different in the PHP class. We have some that have the same "✓ Signed out" and "✓ Signed in" instead of a sign-in button. But there are others that didn't sign out yesterday that do have access to that button.
