### ISSUE TITLE
Fix attendance statistics showing Fridays

### ISSUE THREAD

**Issue by JakeKaad** [epicodus/epicenter#186]
In _views/students/show.html_ on line 31 we are using `@student.cohort.list_class_days.each`.  Should we change `list_class_days` to exclude Fridays as well? 

On a related note, on that page, it would be nice to have the date include the day so instead of `August 10, 2015` it would be `Thursday August 10, 2015`.

**Comment by chrisjoywebb** [comment]
Yup, can do. Fridays are optional for attendance now right?

**Comment by JakeKaad** [comment]
Yep, we aren't counting them in the attendance statistics.
