### ISSUE TITLE
Handle bank account verification updates

### ISSUE THREAD

**Issue by michaelrkn** [epicodus/epicenter#81]
Currently, we don't do anything when a bank account verification succeeds or fails. We should:

* see if we get notified by a Balanced callback;
* assuming there is one, update the status of the account or destroy it;
* notify the user by email.

**Comment by jenmccarthy** [comment]
As of 6/1/2015 Stripe does not send any webhooks when the bank account is verified. This is something that is on the checklist for when ACH comes out of beta.

**Comment by chrisjoywebb** [comment]
Moving all issues to PivotalTracker.
