### ISSUE TITLE
ActiveRecord::ConnectionNotEstablished

### ISSUE THREAD

**Issue by UbuntuEvangelist** [epicodus/epicenter#837]
![Screenshot from 2022-10-06 03-15-01](https://user-images.githubusercontent.com/1058663/194165151-c85ed7f5-253c-4cd1-adb5-45af46c6eb10.png) - connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "root" does not exist:

**Comment by mgoren** [comment]
Sorry I just saw this for some reason. That looks like the postgres user does not exist. You should be able to create a postgres user by doing `createdb $USER`, tho I'm not really sure if that would work from the root account!
