### ISSUE TITLE
Allow admins to add attendance records

### ISSUE THREAD

**Issue by michaelrkn** [epicodus/epicenter#89]
For students who forgot to sign in.

**Comment by michaelrkn** [comment]
I'm thinking that the UI could simply have a page where you choose a student, choose a date, and say whether they were on-time, tardy, or absent. After submitting, the backend will determine whether a record needs to be created, updated, or destroyed.

If this is the approach we take, this and #90 will be closed together.

**Comment by dustinbrownman** [comment]
I feel like of this should be decoupling the attendance record's date from the `created_at` field. I'm picturing adding a `date` property that is by default set after an attendance record is created, but can be updated if need be. I just don't like the idea of changing the `created_at` to a time that different than when the record was actually created.

**Comment by michaelrkn** [comment]
Yes, makes sense.
